server:
  port: 9001
spring:
  application:
    name: common
# JWT
jwt:
  header: Authorization
  secret: scup08
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth/
      refresh: refresh
      register: register